(define (read-words)
  (let loop ((words '()) (word ""))
    (if (eof-object? (peek-char))
        (if (> (string-length word) 0)
            (reverse (cons word words))
            (reverse words))
        (let ((char (read-char)))
          (if (or (equal? char #\newline)
                  (equal? char #\space)
                  (equal? char #\tab))
              (if (> (string-length word) 0)
                  (loop (cons word words) "")
                  (loop words word))
              (loop words (string-append word (string char))))))))