(define (save-data data path)
  (let ((port (open-output-file path #:exists 'update)))
    (write data port)
    (close-output-file)))

(define (load-file path)
  (let ((port (open-input-file path)))
    (let ((r (read port)))
      (close-input-file)
      r)))

(define (count-lines path)
  (let ((port (open-input-file path)))
    (let loop ((lines 0) (chars 0))
      (if (eof-object? (peek-char port)))
      (begin (close-input-file)
             (if (> chars 0)
                 (+ lines 1)
                 lines))
      (if (equal? (read-char port) #\newline)
          (if (> chars 0)
              (loop (+ lines 1) 0)
              (loop lines 0))
          (loop lines (+ chars 1))))))